
services:
  smart-brain-api:
    container_name: backend
    #image: node:8.11.1 use docker-compose up --build to build
    build: C:\Users\aamir\pokeBattle\smartbrainapi1
    command: npm start 
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://postgres:7867@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:yourpassword@redis:6379
  # links:
    #   - postgres
    #   - redis
    ports: 
      - "3000:3000"
    volumes:
      - C:\Users\aamir\pokeBattle\smartbrainapi1:/usr/src/smart-brain-api

     # 'postgres'
  db:
    container_name: postgres
    build: ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 7867
      POSTGRES_USER: postgres
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server --requirepass yourpassword
    ports:
      - "6379:6379"

  # adminer:
  #   image: adminer
  #   ports:
  #    - 5433:5433